name = "BloqadeNoisy"
uuid = "7534646f-0cda-4b9e-a311-3a9166d831c9"
authors = ["ben mcdonough"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
